### ISSUE TITLE
`title: str | None` error in `CharShort`

### ISSUE THREAD

**Issue by GDjkhp** [kramcat/CharacterAI#101]
Traceback (most recent call last):
  File "C:\Users\ACER\Desktop\discord-bots\level-up-loser-python-branch\test2.py", line 60, in <module>
    from characterai import aiocai
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\site-packages\characterai\__init__.py", line 8, in <module>
    from .aiocai.client import aiocai
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\site-packages\characterai\aiocai\__init__.py", line 8, in <module>
    from .client import aiocai
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\site-packages\characterai\aiocai\client.py", line 4, in <module>
    from .methods import Methods
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\site-packages\characterai\aiocai\methods\__init__.py", line 1, in <module>
    from .users import Users
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\site-packages\characterai\aiocai\methods\users.py", line 2, in <module>
    from ...types import user
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\site-packages\characterai\types\user.py", line 5, in <module>
    from .character import CharShort
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\site-packages\characterai\types\character.py", line 10, in <module>
    class Character(BaseModel, Avatar):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\site-packages\characterai\types\character.py", line 93, in Character
    title: str | None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by Karvp** [comment]
You should update your Python to at least 3.10
