### ISSUE TITLE
Telegram bot on asyncio and telebot

### ISSUE THREAD

**Issue by trickster0101010101** [kramcat/CharacterAI#109]
I wanted to write code to interact with characters through this library and asyncio + telebot. 

I took the code without asyncio as a basis, which was suggested by the user rmarsu. 

The essence of the problem: the first message reaches the bot steadily and it responds. However, when sending the second message to the bot, it does not reach CAI and the error from the screenshot appears.
![Screenshot_2](https://github.com/kramcat/CharacterAI/assets/135065829/50ee7f5c-8a2f-413d-a0e4-3862eccd6d57)

Error in terminal VS Code:

-1001520627932
hey
AI: Heya.
-1001520627932
Floppa
Exception ignored from cffi callback <function timer_function at 0x000001AD1F923EC0>:
Traceback (most recent call last):
  File "C:\tg-cai\env\Lib\site-packages\curl_cffi\aio.py", line 93, in timer_function
    timer = async_curl.loop.call_later(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 761, in call_later
    timer = self.call_at(self.time() + delay, callback, *args,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 774, in call_at
    self._check_closed()
  File "C:\Python312\Lib\asyncio\base_events.py", line 541, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2024-06-12 17:48:53.578431 Task <Task pending name='Task-11' coro=<ai_response() running at C:\tg-cai\test2.py:14> cb=[_run_until_complete_cb() at C:\Python312\Lib\asyncio\base_events.py:182]> got Future 
<Future pending> attached to a different loop

The code:

```python
import telebot
from characterai import aiocai
import datetime
import time
import asyncio

TOKEN = 'TG_TOKEN'
CHARACTER_API_KEY = 'CAI_TOKEN'

bot = telebot.TeleBot(TOKEN)
client = aiocai.Client(CHARACTER_API_KEY)

async def ai_response(user_message):
    me = await client.get_me()
    async with await client.connect() as chat:
        new, answer = await chat.new_chat(
            'CAI_ID', me.id
        )
        response = await chat.send_message(
            'CAI_ID', new.chat_id, user_message
        )
        return response.text

def run_async_ai_response(user_message):
    return asyncio.run(ai_response(user_message))

@bot.message_handler(commands=['ai'])
def handle_ai_request(message):
    chat_id = message.chat.id
    print(chat_id)
    user_message = message.text.split(maxsplit=1)[1]
    print(user_message)
    response_text = run_async_ai_response(user_message)
    print(f'AI: {response_text}')  # Print to console
    bot.send_message(chat_id, response_text)

while True:
    try:
        bot.polling(none_stop=True, timeout=60)
    except Exception as e:
        print(datetime.datetime.now(), e)
        time.sleep(5)
        continue

```

**Comment by trickster0101010101** [comment]
The code:

import telebot
from characterai import aiocai
import datetime
import time
import asyncio

TOKEN = '6915020423:AAElGeEytl5a8Uev-igXjEVplX7t4rfVQoI'
CHARACTER_API_KEY = '288d1fe29519b9f8a5e421ebad5d7291fade96d8'

bot = telebot.TeleBot(TOKEN)
client = aiocai.Client(CHARACTER_API_KEY)

async def ai_response(user_message):
    me = await client.get_me()
    async with await client.connect() as chat:
        new, answer = await chat.new_chat(
            'thep9Jza4nSUQQ_ok7YCEI2uMim5oH9OXcVUyo5-C7E', me.id
        )
        response = await chat.send_message(
            'thep9Jza4nSUQQ_ok7YCEI2uMim5oH9OXcVUyo5-C7E', new.chat_id, user_message
        )
        return response.text

def run_async_ai_response(user_message):
    return asyncio.run(ai_response(user_message))

@bot.message_handler(commands=['ai'])
def handle_ai_request(message):
    chat_id = message.chat.id
    print(chat_id)
    user_message = message.text.split(maxsplit=1)[1]
    print(user_message)
    response_text = run_async_ai_response(user_message)
    print(f'AI: {response_text}')  # Print to console
    bot.send_message(chat_id, response_text)

while True:
    try:
        bot.polling(none_stop=True, timeout=60)
    except Exception as e:
        print(datetime.datetime.now(), e)
        time.sleep(5)
        continue
