### ISSUE TITLE
What might be causing this error?

### ISSUE THREAD

**Issue by meet447** [kramcat/CharacterAI#14]
Traceback (most recent call last):
  File "C:\Users\meets\PycharmProjects\AI-Vtuber\eleven labs.py", line 8, in <module>
    client = pyCAI(token)
  File "C:\Users\meets\PycharmProjects\AI-Vtuber\venv\lib\site-packages\characterai\characterai.py", line 55, in __init__
    self.browser = sync_playwright().start().firefox.launch(headless=headless)
  File "C:\Users\meets\PycharmProjects\AI-Vtuber\venv\lib\site-packages\playwright\sync_api\_generated.py", line 14723, in launch
    self._sync(
  File "C:\Users\meets\PycharmProjects\AI-Vtuber\venv\lib\site-packages\playwright\_impl\_sync_base.py", line 109, in _sync
    return task.result()
  File "C:\Users\meets\PycharmProjects\AI-Vtuber\venv\lib\site-packages\playwright\_impl\_browser_type.py", line 95, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "C:\Users\meets\PycharmProjects\AI-Vtuber\venv\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\meets\PycharmProjects\AI-Vtuber\venv\lib\site-packages\playwright\_impl\_connection.py", line 482, in wrap_api_call
    return await cb()
  File "C:\Users\meets\PycharmProjects\AI-Vtuber\venv\lib\site-packages\playwright\_impl\_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Executable doesn't exist at C:\Users\meets\AppData\Local\ms-playwright\firefox-1408\firefox\firefox.exe
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.                                                                         ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝

**Comment by superalix** [comment]
are playwright browsers installed? run playwright install in python console

**Comment by kramcat** [comment]
try `python -m playwright install`

**Comment by meet447** [comment]
Fixed it had to download the browser using command in terminal thanks for your help guys
