### ISSUE TITLE
I stuck at get chat

### ISSUE THREAD

**Issue by jinghuacao** [kramcat/CharacterAI#22]
My issue is at this line

`import asyncio
from characterai import PyAsyncCAI

async def main():
    Token='**********************'
    client = PyAsyncCAI(Token)
    await client.start()

    char = 'y9ChWSyBEiCcpo1npsilkLZ_UR3qrhaobMWUbuxs-e8'

    # Save tgt and history_external_id 
    # to avoid making a lot of requests
    chat = await client.chat.get_chat(char)
`

Traceback (most recent call last):
  File "cai.py", line 37, in <module>
    asyncio.run(main())
  File "d:\ProgramData\Anaconda3\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "d:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  **File "cai.py", line 13, in main
    chat = await client.chat.get_chat(char)**
  File "d:\ProgramData\Anaconda3\lib\site-packages\characterai\pyasynccai.py", line 364, in get_chat
    return await PostResponse(
  File "d:\ProgramData\Anaconda3\lib\site-packages\characterai\pyasynccai.py", line 66, in PostResponse
    await page.evaluate(
  File "d:\ProgramData\Anaconda3\lib\site-packages\playwright\async_api\_generated.py", line 8653, in evaluate
    await self._impl_obj.evaluate(
  File "d:\ProgramData\Anaconda3\lib\site-packages\playwright\_impl\_page.py", line 395, in evaluate
    return await self._main_frame.evaluate(expression, arg)
  File "d:\ProgramData\Anaconda3\lib\site-packages\playwright\_impl\_frame.py", line 277, in evaluate
    await self._channel.send(
  File "d:\ProgramData\Anaconda3\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "d:\ProgramData\Anaconda3\lib\site-packages\playwright\_impl\_connection.py", line 482, in wrap_api_call
    return await cb()
  File "d:\ProgramData\Anaconda3\lib\site-packages\playwright\_impl\_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: NetworkError when attempting to fetch resource.
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x000002096D7FA280>
Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\lib\asyncio\base_subprocess.py", line 126, in __del__
  File "d:\ProgramData\Anaconda3\lib\asyncio\base_subprocess.py", line 104, in close
  File "d:\ProgramData\Anaconda3\lib\asyncio\proactor_events.py", line 108, in close
  File "d:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 719, in call_soon
  File "d:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed

**Comment by kramcat** [comment]
try on v0.7.0

**Comment by kramcat** [comment]
fixed on v0.8.0
