### ISSUE TITLE
unable to use versions 0.2.6 and 0.2.7

### ISSUE THREAD

**Issue by mutethecat** [kramcat/CharacterAI#4]
if i try to install those versions i get this.

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Hex\AppData\Local\Temp\pip-install-9j_3ogkx\characterai_03569ba5445d41f7926cb60078390a46\setup.py", line 4, in <module>
          long_description = readme.read()
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 155: character maps to <undefined>
      [end of output]

**Comment by kramcat** [comment]
The error is not from the side of the library, I tried to reinstall, install where this library did not exist yet, but I had no problems. At least with version 0.2.7

**Comment by mutethecat** [comment]
strange... i was able to install it by downloading the repository, making the readme blank, and running the setup.py
