### ISSUE TITLE
There is smth wrong with execution

### ISSUE THREAD

**Issue by Miedzymorzz3** [kramcat/CharacterAI#54]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\pythonProject5\Chatty.py", line 10, in <module>
    client.start(headless=True)
  File "C:\Users\User\PycharmProjects\pythonProject5\venv\Lib\site-packages\characterai\characterai.py", line 103, in start
    self.browser = self.playwright.firefox.launch(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\pythonProject5\venv\Lib\site-packages\playwright\sync_api\_generated.py", line 14778, in launch
    self._sync(
  File "C:\Users\User\PycharmProjects\pythonProject5\venv\Lib\site-packages\playwright\_impl\_sync_base.py", line 109, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\pythonProject5\venv\Lib\site-packages\playwright\_impl\_browser_type.py", line 96, in launch
    Browser, from_channel(await self._channel.send("launch", params))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\pythonProject5\venv\Lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\pythonProject5\venv\Lib\site-packages\playwright\_impl\_connection.py", line 482, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\pythonProject5\venv\Lib\site-packages\playwright\_impl\_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._api_types.Error: Executable doesn't exist at C:\Users\User\AppData\Local\ms-playwright\firefox-1424\firefox\firefox.exe
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║ 
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝

Despite me making in headless=False , it still requires browser . How can i make this work only in terminal. Any help is appriceated, thanks in advance.

**Comment by reciprocated** [comment]
> Traceback (most recent call last): File "C:\Users\User\PycharmProjects\pythonProject5\Chatty.py", line 10, in client.start(headless=True) File "C:\Users\User\PycharmProjects\pythonProject5\venv\Lib\site-packages\characterai\characterai.py", line 103, in start self.browser = self.playwright.firefox.launch( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\User\PycharmProjects\pythonProject5\venv\Lib\site-packages\playwright\sync_api_generated.py", line 14778, in launch self._sync( File "C:\Users\User\PycharmProjects\pythonProject5\venv\Lib\site-packages\playwright_impl_sync_base.py", line 109, in _sync return task.result() ^^^^^^^^^^^^^ File "C:\Users\User\PycharmProjects\pythonProject5\venv\Lib\site-packages\playwright_impl_browser_type.py", line 96, in launch Browser, from_channel(await self._channel.send("launch", params)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\User\PycharmProjects\pythonProject5\venv\Lib\site-packages\playwright_impl_connection.py", line 61, in send return await self._connection.wrap_api_call( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\User\PycharmProjects\pythonProject5\venv\Lib\site-packages\playwright_impl_connection.py", line 482, in wrap_api_call return await cb() ^^^^^^^^^^ File "C:\Users\User\PycharmProjects\pythonProject5\venv\Lib\site-packages\playwright_impl_connection.py", line 97, in inner_send result = next(iter(done)).result() ^^^^^^^^^^^^^^^^^^^^^^^^^ playwright._impl._api_types.Error: Executable doesn't exist at C:\Users\User\AppData\Local\ms-playwright\firefox-1424\firefox\firefox.exe ╔════════════════════════════════════════════════════════════╗ ║ Looks like Playwright was just installed or updated. ║ ║ Please run the following command to download new browsers: ║ ║ ║ ║ playwright install ║ ║ ║ ║ <3 Playwright Team ║ ╚════════════════════════════════════════════════════════════╝
> 
> Despite me making in headless=False , it still requires browser . How can i make this work only in terminal. Any help is appriceated, thanks in advance.

`playwright install`  in terminal.
