### ISSUE TITLE
JSON decoder ERROR: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by kaiyga** [kramcat/CharacterAI#90]
JSON decoder ERROR

I get your code exemple. But this is located somewhere in the depths of the libraries and in my code, it also does not work:p  

```py
from characterai import PyCAI

client = PyCAI('##### MY TOKEN:P #######') # Yes, i paste my token;3

char = input('Enter CHAR: ')

chat = client.chat.get_chat(char)

participants = chat['participants']

if not participants[0]['is_human']:
    tgt = participants[0]['user']['username']
else:
    tgt = participants[1]['user']['username']

while True:
    message = input('You: ')

    data = client.chat.send_message(
        chat['external_id'], tgt, message
    )

    name = data['src_char']['participant']['name']
    text = data['replies'][0]['text']

    print(f"{name}: {text}")

```

```bash
Enter CHAR: YntB_ZeqRq2l_aVf2gWDCZl4oBttQzDvhj9cXafWcF8

Traceback (most recent call last):
  File "/home/kaiy/Documents/Git/CLONED/WifuSoul/Soul-of-W/addons/CharacterAI/t.py", line 7, in <module>
    chat = client.chat.get_chat(char)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kaiy/Documents/Git/CLONED/WifuSoul/Soul-of-W/env/lib/python3.11/site-packages/characterai/characterai.py", line 531, in get_chat
    return PyCAI.request(
           ^^^^^^^^^^^^^^
  File "/home/kaiy/Documents/Git/CLONED/WifuSoul/Soul-of-W/env/lib/python3.11/site-packages/characterai/characterai.py", line 69, in request
    data = response.json()
           ^^^^^^^^^^^^^^^
  File "/home/kaiy/Documents/Git/CLONED/WifuSoul/Soul-of-W/env/lib/python3.11/site-packages/tls_client/response.py", line 38, in json
    return json.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
 ```

**Comment by kaiyga** [comment]
I did check request, and i get this html page. But it is not JSON  
```
\  <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131}button,html{font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji}@media (prefers-color-scheme:dark){body{background-color:#222;color:#d9d9d9}body a{color:#fff}body a:hover{color:#ee730a;text-decoration:underline}body .lds-ring div{border-color:#999 transparent transparent}body .font-red{color:#b20f03}body .big-button,body .pow-button{background-color:#4693ff;color:#1d1d1d}body #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+)}}body{display:flex;flex-direction:column;min-height:100vh}body.no-js .loading-spinner{visibility:hidden}body.no-js .challenge-running{display:none}body.dark{background-color:#222;color:#d9d9d9}body.dark a{color:#fff}body.dark a:hover{color:#ee730a;text-decoration:underline}body.dark .lds-ring div{border-color:#999 transparent transparent}body.dark .font-red{color:#b20f03}body.dark .big-button,body.dark .pow-button{background-color:#4693ff;color:#1d1d1d}body.dark #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body.dark #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+)}body.light{background-color:transparent;color:#313131}body.light a{color:#0051c3}body.light a:hover{color:#ee730a;text-decoration:underline}body.light .lds-ring div{border-color:#595959 transparent transparent}body.light .font-red{color:#fc574a}body.light .big-button,body.light .pow-button{background-color:#003681;border-color:#003681;color:#fff}body.light #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body.light #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI2ZjNTc0YSIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjZmM1NzRhIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+)}a{background-color:transparent;color:#0051c3;text-decoration:none;transition:color .15s ease}a:hover{color:#ee730a;text-decoration:underline}.main-content{margin:8rem auto;max-width:60rem;width:100%}.heading-favicon{height:2rem;margin-right:.5rem;width:2rem}@media (width <= 720px){.main-content{margin-top:4rem}.heading-favicon{height:1.5rem;width:1.5rem}}.footer,.main-content{padding-left:1.5rem;padding-right:1.5rem}.main-wrapper{align-items:center;display:flex;flex:1;flex-direction:column}.font-red{color:#b20f03}.spacer{margin:2rem 0}.h1{font-size:2.5rem;font-weight:500;line-height:3.75rem}.h2{font-weight:500}.core-msg,.h2{font-size:1.5rem;line-height:2.25rem}.body-text,.core-msg{font-weight:400}.body-text{font-size:1rem;line-height:1.25rem}@media (width <= 720px){.h1{font-size:1.5rem;line-height:1.75rem}.h2{font-size:1.25rem}.core-msg,.h2{line-height:1.5rem}.core-msg{font-size:1rem}}#challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI2ZjNTc0YSIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjZmM1NzRhIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+);padding-left:34px}#challenge-error-text,#challenge-success-text{background-repeat:no-repeat;background-size:contain}#challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=);padding-left:42px}.text-center{text-align:center}.big-button{border:.063rem solid #0051c3;border-radius:.313rem;font-size:.875rem;line-height:1.313rem;padding:.375rem 1rem;transition-duration:.2s;transition-property:background-color,border-color,color;transition-timing-function:ease}.big-button:hover{cursor:pointer}.captcha-prompt:not(.hidden){display:flex}@media (width <= 720px){.captcha-prompt:not(.hidden){flex-wrap:wrap;justify-content:center}}.pow-button{background-color:#0051c3;color:#fff;margin:2rem 0}.pow-button:hover{background-color:#003681;border-color:#003681;color:#fff}.footer{font-size:.75rem;line-height:1.125rem;margin:0 auto;max-width:60rem;width:100%}.footer-inner{border-top:1px solid #d9d9d9;padding-bottom:1rem;padding-top:1rem}.clearfix:after{clear:both;content:"";display:table}.clearfix .column{float:left;padding-right:1.5rem;width:50%}.diagnostic-wrapper{margin-bottom:.5rem}.footer .ray-id{text-align:center}.footer .ray-id code{font-family:monaco,courier,monospace}.core-msg,.zone-name-title{overflow-wrap:break-word}@media (width <= 720px){.diagnostic-wrapper{display:flex;flex-wrap:wrap;justify-content:center}.clearfix:after{clear:none;content:none;display:initial;text-align:center}.column{padding-bottom:2rem}.clearfix .column{float:none;padding:0;width:auto;word-break:keep-all}.zone-name-title{margin-bottom:1rem}}.loading-spinner{height:76.391px}.lds-ring{display:inline-block;position:relative}.lds-ring,.lds-ring div{height:1.875rem;width:1.875rem}.lds-ring div{animation:lds-ring 1.2s cubic-bezier(.5,0,.5,1) infinite;border:.3rem solid transparent;border-radius:50%;border-top-color:#313131;box-sizing:border-box;display:block;position:absolute}.lds-ring div:first-child{animation-delay:-.45s}.lds-ring div:nth-child(2){animation-delay:-.3s}.lds-ring div:nth-child(3){animation-delay:-.15s}@keyframes lds-ring{0%{transform:rotate(0)}to{transform:rotate(1turn)}}@media screen and (-ms-high-contrast:active),screen and (-ms-high-contrast:none){.main-wrapper,body{display:block}}</style><meta http-equiv="refresh" content="375"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '3',cZone: "beta.character.ai",cType: 'managed',cNounce: '37495',cRay: '8621b71f3d5d3a56',cHash: '9cd003f7a674a0e',cUPMDTk: "\/chat\/history\/continue\/?__cf_chl_tk=4Kp58zN.nksQjBiQc3OrLvQmMPzNyt7sjBMRGEvCK_w-1710057041-0.0.1.1-1642",cFPWv: 'b',cTTimeMs: '1000',cMTimeMs: '375000',cTplV: 5,cTplB: 'cf',cK: "visitor-time",fa: "\/chat\/history\/continue\/?__cf_chl_f_tk=4Kp58zN.nksQjBiQc3OrLvQmMPzNyt7sjBMRGEvCK_w-1710057041-0.0.1.1-1642",md: "WSfKVgdGZMDbLvAcirko2Xll0Q6TXENjf.wW3t7VV70-1710057041-1.1.1.1-rsS61AwMOZVKvue8z9iVTyrvBQhOSN8cofbCNnXhH4YwOS3uYNaccFMZ1yHKcgM50ohshVlYj8_bWcyRZrOZMp2jVgBYXoTLCQV9vcKNpiT9SQj3.pGkDgO.1hTB_gwFvLQX6iYRmEOmJxw5hIcfosBIqcRcJGtRCJiN_I16GvdZbvogqkt9Rb_Bihs59ZSzac6dRwsZvVB_X7EpJpWO_0J6VtOBLIjXdBjViXvhhRh48e1Fz3X3FyUwGnN8fwtPMMQ4XeS3FY6uXm5dT.ARWQ0P79l0Ju1sAf0g5UdEkvnUiUrpT5mmdqI3SGGsM6eJBqc2v_gKhzioc3k3lgU9tJN6vcmyGBUhdTthNkkVENbVSJw0o_COmKJ_JlBwBWEwCbhBFS3DrDyarD03xT80SOdZk8Wt7bCLrZxxgLA8y8l6gvqkI4MhkLdQicT77TIEQKYgcizyr6iZGZkZ5YXrIW8RF7NyV4eQdyq.RYFQDbc_6Qw8dvp2zOOVSdKDfAZ7Fw3v.rCrpAWSfDy4CFc1XZtaPwAdEbpzZKezQSLghZLsuh9Pli3TiRq_8wGtY0KBooe7TBQ8yp3X4aWDJX1S0fCKRbWW3BB1I6m_lEm9KoxXcyD8a4d9B7NTHJtbRpMuKr1GTSVsVwJH_v6FsrZtI01nMrffqE88MOQSuxuCmVC4QQDlQX.7k6zq4Lf10ACAuSQOWG6p8FVkX1t1qF6e8NjHOrsqyjRVGl3oo6FIxH9orezvAvjSKQ9k6qICBAQCquPMA65Pp5eUabbiAHxT9kzK8PqLMGVGbI65mgeCA4F5hoWKQeP6VDk4MyQwXNNhxJJ_0xPLshKiqp97oWjJX_jZHFqvkgOhMJ6NAuoO7o8Dw6Ju8kJW8CDySLIBci9vCzIqxDjvukcPHJ4YfwMxlyH4OCog528JuEiABrrRN5v0DcNY28hWWtElUAjakql5Dvmr8Uoi_RahuFo6MwjkdEeixT9nUQkXvZpv2.qqXO58l8ddLjroLYFMNxlr_9UF4dXFtEvYrT5U6TAvzQ7iKrqgtsHHPxCerH2Ibi_Arc2Q6Me.yRr4pp6noGIrIa2OnRgYkqDtwiapqPo2MpFUuIVCqD8PofrfwYJhNulTVvID3nseKI.WJ0kE8hEIiJMK5ZwDR92MWnQ4Ec0slf8x0N1piNEh078f7.QTlzdqFn1atqGl67ZjFEzsB1fJ13_W804jqP7ypJUdv0vV1W5_Q2ouNMU3CeYwIruM4isKHictmRl.oNhOhgLptCyCtr37FA177JWGgEXfmxQXaOi21OBOWtGp7Mcm96fzZWL4z53YoSWgTqEjiqOJO56egL1oN6k7MU5A3H9oahA0340U_jzFPYMdsCvBmsLscBbpU_mSajj1qDwKr3.2RFTVWU5aZImVDVGefRum2p4nzTNBDEzkl_OgccTRCQHs5JoVNpd3RrcnzXaEy9rDtBi.gLCNJBdZFYq8Rn_JkZtYUiukmpgDrW4vsjdUqaUNTbyinY.MoXGlEyFvJWf.4jripTk9BdqcMKt1bd3MQ8de.uMx0uxoEigkqVTKAiBaAqMXEPE",mdrd: "ZniztxnTUgFgmRoKQbpuzY9Ejr8whzZoQE7pl7JrBUk-1710057041-1.1.1.1-o2kkYwzTZHx0sdOKQoI7qcMOwH6m.oKkjJD4.4jAU05.e4The0NOdfO8RKpMDgBSzD4Wrp_gUN.28ReeY1Xr16qX7yxK9MQ298Qu_bi4dktHJWVFnfl5jc9dHydAWWSY9QrrRi8bdm6H06Oy8_CRRGnpULVj5HuqhvATG6cfqcW1TG8jkrJs61kNztEndOeSG6flgmCqVYpsoGBrEfRSsUubE1pOYZGQ1rITnuQSso0v2W3_8iCLQ0zDKZxga9QYHI5LrjYFPKOoGXmMeWTgla4ARwGJrAYfu4YHb2V_.yFMbxUeoNkd9F3hn8V1VHi_AeF4Irxat_j0.Vl9w2akgO5cf9nmkY6cnBDLnS0.Emj9qPfipuBZ7s0DlMIoU6AYImKcHmEV_ewXEXrnrwcBeVMGlQrm9dtO7tVHcB1F6vcuXGXgZbN4ngoU4BNLQESSKmdlbyQrD9m6WL5MZkFkbGHHwrJvl85MGs10NvT5ODkH4DAsp63M3cmGmumqcFu1sDGPIjmcEBGjFvWgZdvdMDECMTP8ddXEmvp59Qar_9gRW41OUIiKQSD6Tm3REBwtGyilPiWjJNEmjIz7NmuuQ_WDTzFgIYRqxPQonAEFsD3xb9DUvuUiEhfBJJYM1abf7kp0n9BGbXhzUXzuHvd_ZNpObEFUgf97eU7d_6Eima3MgRsmeEBC4DcozDqEqe7aP.D1mQLYBAxnx1IQHQzplttWyVQ_vYBRBNMpUWhJMvk4Hg60TaZsaQqEye7X9BX6EU7VNLO650Mdrf673aBpeES2cQjnDP81RN08WAf5xFCJt3UtHdS_mTQCnSNm05wfNwfd1.mck7pJYaCT09OgpgdhPvplDVPPyWRoflIt4RT5we22gx3bVqTt51yLcHjEpYzLQGIgSSfmmTjN_g4iD_daC2jDeUGenegJ1AaKHWZQu5PxgnEY5P4LiVpf9aIpsbMkmcsdYMfAGpqiPfryRQrsWtmX0cYrKa3QZ6_9FIfsH2oA2oXDhs.Cvclzexvu7HyLBTgKM6sxxsJbUIoHyVkMB9pkqNS2c72rCVwz7_xNbSSQavN2nt99BBEtaRb.iv9n0RiZmjt8s5_rQoTQ1_ftG2uH.INjJFrFP2cWPgksX1aVkjcqM2nVW.HFUulHFeiBrYuE9pEJdZEmoYEfzxmmf1eGwdmgAO7yYL6I_0vt7F_6_tTJkcxV4PcAzG6FJI.6CWbdcZeHkkVfjAxNF1SDUs59qL7lYLvxzBjHWCEsFkJKQ5JToBGjHOV5UVg8mB0cP6lEEgInNs3f8ylCIt2aLy0dhKX0zdZx7zr2ELx1vkpDQOGP6keL9I1wm8z33iCEaefhaSnqjhg.s2WXWgg4DNsPwkEsEoVRHvxuld5tvgzl.35QE0.ScWefaCLPcMpVWHYiTXrL4jIqyWbcdjec93o9eCJnr_Vgpn4KGMtGSyI_8Lleo8EgtS3XJ60XzKAWW.PU8AN6bxlnYBhkjRqsLLN8D1KxLs9h.oh1D0a5V_ezYEpK7LkAOiJRgeCKr6FRxsoUnc_zA5.7uLq1S74ZDpgeGwqeCBxZjQoI1cW0DFc8zO6EB4UifodX9gCgSqs.rW3Z_QrZ2yyNIDYUXE8hxZ.O5ibEYqptmBAg9hd_HYbOb.UHhsOS9eVTZWnisrhvJODX.OgfVKqT6rs9BEyldpyQDXGN1vUgnrV7wNGkSOsVWAXpW4V_pdG905mJmcY5EjeA8Peak8IrtJKlSyto2IVtA0Wx1UEO2zRAPi2R.zQ.h49pM.oQsAz_2aTqeNbnGS1t2eH2rJCQtCPruKozfHkFHHM5J9maDfD_0Tvi.hBLkElSGTKML2njK97f.qdIQjOU4.CZ2BPMpVDcZ09YQo4dzorCG_EiBhRRAopC5ko3qZchPrwBkfO_KgRBe7XCgddbO_ZkhJlRH.DL5iXUo80NTwfQpKLV5WkV0mgS7rLDZAJifsyy9qDlo1LhlP_4FhBI7YDvyXvZcDTL9bnpBzlt0v2hsiU6sHXEGtyCPK5O8HADZnzEFiuWWNv12zyAsxC43fjLlja7DVe1dVMjLjlC0t2O6Qrhl43r8bSkMU_BE8k3IKKL8DiOtlJ8z3yLLp2Bef19d_ywIgd85iyUjUgU9z62e5uQ.kdUAEmUp_rHSB514Lk2pj97KmH8UvktmcJAzPFtvLkva7QhjX8_7VykB_7gC.ru_LHxB5MI51.p_kVQjGsm4Z4.MzLPu17MprOSQ4Uny6AAyANxVVvqYhXZXGvxROSXsG1rWoH6e7j0uaf3a3.kkcHZ3lA3bUlByNmjAn4NSTQXIprCSQ",cRq: {ru: 'aHR0cHM6Ly9iZXRhLmNoYXJhY3Rlci5haS9jaGF0L2hpc3RvcnkvY29udGludWUv',ra: 'dGxzLWNsaWVudC8xLjAuMQ==',rm: 'UE9TVA==',d: 'ljUoyy0E2Pc2VB7wjdu6BUN6ERYuFrhNOBy41UZBwUFICYIcPoQZKvCBOgN/56jMdEojDMPCE/osrjYa6qLq2NlAG9wr260nPL8MYO2XUyIFzJIw2LJ+yQ2AKf9cfM134YPm1fV/GUTnwfgGoeyAR54sSE65vzkc7Pgh9q+NU21cNeraf25GFPWoIzpG6yw3wIZhykn9nG7zCv1UNrDROTvCWC9SjdSkLO6yJEPnEu04zNE7u9CrSruR3OYVvSaC4J8x7+jMpxypFQzygsJSkLEjqrd0WUqhv5CBwD7XblsGsJJnNyzBViVBDSzfJ029neRFRGdwuoBLIekzP70wPrHU3AMGUZoAHPf8/rXn6STku0/7qwFrR5g9flnmhAJmPUok67NJknkVDBhJA1jVZK9IIce+dvvjJPm7ZfD3RfiAyuY9huKYYtf2CpDYzjpDVdyNNJdUfEnRAYEQylHpE7hDKdpa9IpGXCOY+EvSnuhieWYSkklVLwguO9/bbsRNZElPXgRhzpJJTDPvLYe44in3uT/c23OPWKdI3qLGhejTQYpH9gPGrgjP+t92XW2I98mV05DtlJr6VmvhKbVYXysqJwY70blbsUDIN7SymKg=',t: 'MTcxMDA1NzA0MS44MjQwMDA=',cT: Math.floor(Date.now() / 1000),m: 'zNbhNaO2MGf1puoEBC/sVu9eduPRMp5IGneWj/UvC7Q=',i1: 'Wz4Hs7VSPHlTnwycnWPpzQ==',i2: 'NxYkDrv3xXRt1BLWOSjFsQ==',zh: '3MzEEr4KLflmeMqd8UHKRwLX7AlBIHlHXAkcvB3KPTI=',uh: 'PXA3WvSHsl88rn3RWQHt8RAU5cTq87S3MY+UJ6IpyfA=',hh: 'YfIreubNI/6hc4NG9htqteP1V6Jt4WFaxTZZalkN138=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page/v1?ray=8621b71f3d5d3a56';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/chat\/history\/continue\/?__cf_chl_rt_tk=4Kp58zN.nksQjBiQc3OrLvQmMPzNyt7sjBMRGEvCK_w-1710057041-0.0.1.1-1642" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script><script defer src="https://static.cloudflareinsights.com/beacon.min.js/v84a3a4012de94ce1a686ba8c167c359c1696973893317" integrity="sha512-euoFGowhlaLqXsPWQ48qSkBSCFs3DPRyiwVu3FjR96cMPx+Fr+gpWRhIafcHwqwCqWS42RZhIudOvEI+Ckf6MA==" data-cf-beacon='{"rayId":"8621b71f3d5d3a56","b":1,"version":"2024.2.4","token":"de6c8a8324c04a50b30bdeb96bc8d410"}' crossorigin="anonymous"></script>
</body></html> 



Traceback (most recent call last):
  File "/home/kaiy/Documents/Git/CLONED/WifuSoul/Soul-of-WFF/addons/CharacterAI/t.py", line 7, in <module>
    chat = client.chat.get_chat(char)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kaiy/Documents/Git/CLONED/WifuSoul/Soul-of-WFF/env/lib/python3.11/site-packages/characterai/characterai.py", line 533, in get_chat
    return PyCAI.request(
           ^^^^^^^^^^^^^^
  File "/home/kaiy/Documents/Git/CLONED/WifuSoul/Soul-of-WFF/env/lib/python3.11/site-packages/characterai/characterai.py", line 70, in request
    data = response.json()
           ^^^^^^^^^^^^^^^
  File "/home/kaiy/Documents/Git/CLONED/WifuSoul/Soul-of-WFF/env/lib/python3.11/site-packages/tls_client/response.py", line 38, in json
    return json.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by scuderia666** [comment]
same error

**Comment by Karvp** [comment]
Just update ur tls_client to the latest version, it is fixed

**Comment by Leaderofepic134** [comment]
> Just update ur tls_client to the latest version, it is fixed.
> 
> Edit: Command here for who needs `pip install tls-client==1.0.1`

Tried it and it doesn't work.

**Comment by Karvp** [comment]
> > Just update ur tls_client to the latest version, it is fixed.
> > Edit: Command here for who needs `pip install tls-client==1.0.1`
> 
> Tried it and it doesn't work.

As @kaiyga stated, this problem occur because CloudFlare is not solved. Try using some library to pass it though. For me, I just need to update tls-client. You can try [cloudscraper](https://github.com/venomous/cloudscraper). If it doesn't work, I can't help you.

**Comment by kaiyga** [comment]
#93
