### ISSUE TITLE
"Expecting value" JSONDecodeError

### ISSUE THREAD

**Issue by Canadian599xx** [kramcat/CharacterAI#99]
Traceback (most recent call last):
  File "C:\Users\nolan\PycharmProjects\LEARNINGTOAI\CAi.py", line 10, in <module>
    chat = client.chat.get_chat(char)
  File "C:\Users\nolan\PycharmProjects\LEARNINGTOAI\.venv\lib\site-packages\characterai\characterai.py", line 531, in get_chat
    return PyCAI.request(
  File "C:\Users\nolan\PycharmProjects\LEARNINGTOAI\.venv\lib\site-packages\characterai\characterai.py", line 69, in request
    data = response.json()
  File "C:\Users\nolan\PycharmProjects\LEARNINGTOAI\.venv\lib\site-packages\tls_client\response.py", line 38, in json
    return json.loads(self.text, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

after the character URL is entered into the program, it throws out this error, not sure what for or how to fix it, any solutions are appreciated!

**Comment by kramcat** [comment]
Fixed in the new version
